# Generated by Django 3.0.2 on 2020-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_doctorappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_image',
            field=models.FileField(upload_to=''),
        ),
    ]
