# Generated by Django 3.0.2 on 2020-03-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200328_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
