# Generated by Django 3.0.2 on 2020-03-30 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200330_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
