# Generated by Django 3.0.2 on 2020-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200330_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
