# Generated by Django 3.0.2 on 2020-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20200330_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='problem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
