# Generated by Django 3.0.2 on 2020-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_auto_20200401_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='advice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
