# Generated by Django 3.0.2 on 2020-05-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.IntegerField(default=1),
        ),
    ]
