# Generated by Django 3.0.2 on 2020-04-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='organisation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
