# Generated by Django 3.0.2 on 2020-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
